python3: can't open file '@Telegram.py': [Errno 2] No such file or directory
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
My name is xiaoya.
And I'm 17 years old now.

My name is xiaoya.
And I'm 17 years old now.

replying...
replying...
罗织经.txt 22
[C]高中史论集合.txt 65
replying...
人生7.txt 29
replying...
语文.txt 81
replying...
Python自学笔记.txt 105
replying...
人生7.txt 30
replying...
2015年六级词汇[Ramdom].txt 216
replying...
人生7.txt 31
replying...
文言文.txt 72
replying...
2016年全国高考英语大纲词汇.txt 102
replying...
2016年全国高考英语大纲词汇.txt 103
replying...
Python自学笔记.txt 106
replying...
2016年全国高考英语大纲词汇.txt 104
replying...
罗织经.txt 23
replying...
2016年全国高考英语大纲词汇.txt 105
replying...
2015年六级词汇[Ramdom].txt 217
replying...
2015年六级词汇[Ramdom].txt 218
replying...
[simple]《世说新语》—YS remix.txt 146
replying...
文言文.txt 73
replying...
人生7.txt 32
replying...
Python自学笔记.txt 107
replying...
人生7.txt 33
replying...
人生7.txt 34
replying...
2016年全国高考英语大纲词汇.txt 106
replying...
[C]高中史论集合.txt 66
replying...
语文.txt 82
replying...
2015年六级词汇[Ramdom].txt 219
replying...
2016年全国高考英语大纲词汇.txt 107
replying...
人生7.txt 35
replying...
[C]高中史论集合.txt 67
replying...
Python自学笔记.txt 108
replying...
2015年六级词汇[Ramdom].txt 220
replying...
文言文.txt 74
replying...
罗织经.txt 24
replying...
2016年全国高考英语大纲词汇.txt 108
replying...
[C]高中史论集合.txt 68
replying...
2015年六级词汇[Ramdom].txt 221
replying...
[C]高中史论集合.txt 69
replying...
[simple]《世说新语》—YS remix.txt 147
replying...
文言文.txt 75
replying...
[C]高中史论集合.txt 70
replying...
Python自学笔记.txt 109
replying...
2015年六级词汇[Ramdom].txt 222
replying...
2015年六级词汇[Ramdom].txt 223
replying...
Traceback (most recent call last):
  File "Telegram.py", line 25, in <module>
    bot.polling()
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 222, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 246, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 103, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/root/.local/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "Telegram.py", line 21, in handle
    result = TGx.reply(msg.text)
  File "/root/Xiaoya/__Xiaoya__.py", line 165, in reply
    return self.baike(msg)
  File "/root/Xiaoya/__Xiaoya__.py", line 132, in baike
    from Plugins.Extensions.GetBaike.Baike import main as baike
  File "/root/Xiaoya/Plugins/Extensions/GetBaike/Baike.py", line 1, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
